# Generated by Django 3.1.3 on 2020-11-09 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duracion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
