# Generated by Django 3.1.3 on 2020-11-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_plan_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='imagen',
            field=models.ImageField(null=True, upload_to='planes'),
        ),
    ]
