# Generated by Django 3.1.3 on 2020-11-13 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planes', '0003_plan_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Contratados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('fechaPlan', models.DateTimeField(default=django.utils.timezone.now)),
                ('idPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
