# Generated by Django 3.1.3 on 2020-11-13 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planes', '0005_auto_20201113_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_contratado',
            name='idPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plan'),
        ),
        migrations.AlterField(
            model_name='plan_contratado',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
